// src/components/textcat/RegionSelect.vue
<script setup lang="ts">
import { t } from "../../i18n";
import { catalog, srcRegion } from "../state";
</script>

<template>
  <label>
    {{ `[${t("region")}: ` }}
    <select v-model="srcRegion">
      <option value=""></option>
      <option v-for="region in catalog?.regions" :key="region" :value="region">
        {{ region }}
      </option>
    </select>
    {{ "]" }}
  </label>
</template>

// src/components/textcat/regionSelect.tsx
import { FunctionalComponent, h } from "preact";
import { StateUpdater } from "preact/hooks";
import { t } from "../../i18n";

interface Props {
  regions: Set<string>;
  srcRegion: string;
  setSrcRegion: StateUpdater<string>;
}

const RegionSelect: FunctionalComponent<Props> = (props: Props) => (
  <label>
    {`[${t("region")}: `}
    <select
      value={props.srcRegion}
      onChange={(e): void =>
        props.setSrcRegion((e.target as HTMLSelectElement).value)
      }
    >
      <option value=""></option>
      {Array.from(props.regions)
        .sort()
        .map(region => (
          <option key={region} value={region}>
            {region}
          </option>
        ))}
    </select>
    {"]"}
  </label>
);

export default RegionSelect;
